config/routes.rb
Soulyhiphop::Application.routes.draw do
  resources :hiphop_sites

  resources :bars
  root "bars#index"

  resources :messengers, only: :update

  

end

app/models/bar.rb
class Bar < ActiveRecord::Base
  validates :title, :body, :authors, :entry_url, :description, :published_at, presence: true
  validates :title, uniqueness: true
  validates :entry_url, uniqueness: true
end

app/models/hiphop_site.rb
class HiphopSite < ActiveRecord::Base
end

app/controllers/aggregator.rb
require 'rubygems'
require 'feed-normalizer'
require 'open-uri'
# http://ruby.dzone.com/articles/ruby-rss-aggregator
#Define URL and Parse Feed
feed_url = gets.chomp
rss = FeedNormalizer::FeedNormalizer.parse open(feed_url)

#Quit if  no articles
exit unless rss.entries.length > 0

#Read entries
rss.entries.each do |entry|
  title = entry.title
  body = entry.content
  authors = entry.authors.join(', ') rescue ''
  entry_url = entry.urls.first
  description = entry.description
  published_at = entry.date_published
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def index
    @bars = Bar.all
  end
end

app/controllers/hiphop_sites_controller.rb
class HiphopSitesController < ApplicationController
  skip_before_filter(:verify_authenticity_token)
  def create
   #Write entries from form to database
    HiphopSite.create hiphop_site_params
    redirect_to hiphop_sites_path
  end

  def new
    @hiphop_site = HiphopSite.new
  end

  def index
    @hiphop_sites = HiphopSite.all
  end

  def edit
    @hiphop_site = HiphopSite.find(params[:id])
  end

  def update
    @hiphop_site = HiphopSite.find(params[:id])
    @hiphop_site.update_attributes(hiphop_site_params)
    redirect_to hiphop_sites_path
  end
  protected

  def hiphop_site_params
    params.require(:hiphop_site).permit(:url, :description, :image_url)
  end
end

app/controllers/messengers_controller.rb
class MessengersController < ApplicationController
  before_filter :make_sure_we_have_entries

  def update
    #Read entries
    new_bars_count = rss_entries.select do | entry|
      bar = Bar.new
      bar.title = entry.title
      bar.body = entry.content
      bar.authors = entry.authors.join(', ') rescue ''
      bar.entry_url = entry.urls.first
      bar.description = entry.description
      bar.published_at = entry.date_published
      bar.save
    end.count
    flash.notice = "#{new_bars_count} bars created"
    redirect_to root_path

  end
  def rss_entries
    return @rss.entries unless @rss.nil?
    feed_url = HiphopSite.first.url
    #feed_url = 'http://www.okayplayer.com/feed'
    @rss = FeedNormalizer::FeedNormalizer.parse open(feed_url)
    @rss.entries
  end
  def make_sure_we_have_entries
    #Quit if  no articles
    redirect_to root_path if rss_entries.length.zero?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/hiphop_sites_helper.rb
module HiphopSitesHelper
end

app/views/bars/index.html.erb
<h1>Latest Bars</h1>
<ul>
<% @bars.each do |bar| %>
  <li>
    <%= link_to bar.title, bar.entry_url%>
  </li>
<% end %>
</ul>

app/views/hiphop_sites/edit.html.erb
<h1>Edit Site</h1>

<%= form_for @hiphop_site do |form| %>
  <div>
    <%= form.label :description, "Description" %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label :url, "Enter URL" %>
    <%= form.text_field :url %>
  </div>
  <div>
    <%= form.label :image_url, "Enter Image URL" %>
    <%= form.text_field :image_url %>
  </div>
  <%= form.submit %>
<% end %>
<br><br>

app/views/hiphop_sites/index.html.erb
<h1>Hip Hop Sites</h1>
<ul>
  <% @hiphop_sites.each do |hip| %>
    <li>
      <%= image_tag hip.image_url %>
      <%= link_to hip.description, hip.url %>
      <%= link_to "edit", edit_hiphop_site_path(hip) %>
      <%= button_to "Fetch", messenger_path(hip), method: :patch %>
    </li>
  <% end %>
</ul>

app/views/hiphop_sites/new.html.erb
<h1>Enter New Site</h1>

<%= form_for @hiphop_site do |form| %>
  <div>
    <%= form.label :description, "Description" %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label :url, "Enter URL" %>
    <%= form.text_field :url %>
  </div>
  <div>
    <%= form.label :image_url, "Enter Image URL" %>
    <%= form.text_field :image_url %>
  </div>
  <%= form.submit %>
<% end %>
<br><br>

<hr>
<form action="<%=hiphop_sites_path%>" method="post">
  <div> 
    <label for="url"> Enter URL </label>
    <input id="url" type="url" name="url"/> 
  </div>
  <div> 
    <label for="description"> Site Description </label>
    <input id="description" type="text" name="description" />
  </div>
  <div> 
    <label for="image_url"> Image Url</label>
    <input type="text" name="image_url"/>
  </div> 
  <input type='submit' value="Submit">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soulyhiphop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= link_to "bars", bars_path %>
  <%= link_to "hip hop sites", hiphop_sites_path %>
  <%= link_to "add hip hop site", new_hiphop_site_path %>
</header>
<div id="page">
  <% if flash[:alert] %>
    <P class="flash-error"><%= flash[:alert] %></p>
  <% end %>
  <% if flash[:notice] %>
    <p class="flash-notice"><%= flash[:notice] %></p>
  <% end %>
<%= yield %>
</div>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>